# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71348c58a2ea8f0c7c8f6caa4468c4e893827a05a8f35bbdfea9c76dd3f5223403d0396f9ea66015173997766bff07172200c8ed677b9763b9a0f217af541eff
  google_storage_access_key_id: <%= ENV["GKEY"] %>
  google_storage_secret_access_key: <%= ENV["GACCESS"] %>

test:
  secret_key_base: ea38cc0ceb665753872ef8608532c0e980af2df55eea93e427c427d3af5b63baf5f9a9d76b144601f8e771110f3dbd53d8d49f68fe7e843d6dc2352aa990a978

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_storage_access_key_id: <%= ENV["GKEY"] %>
  google_storage_secret_access_key: <%= ENV["GACCESS"] %>
